id: PD7A77FED
initial_creation_type: input
source_metadata:
  title: Ngawang Samten Lodrö Series
  language: en
  description: 'Texts by and about Khenchen Ngawang Samten Lodrö (ngag dbang bsam
    gtan blo gros, 1868–1931):'
  volume:
    04720812d95c49a39c492c6107b92f89:
      title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara
        Ngawang Samten Lodrö'
      parent: Guru Yoga
    8caee404e96e4c5c86f6bc418b940970:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Prayers
created_at: '2022-03-01T00:59:41.511506'
last_modified_at: '2022-03-01T00:59:41.511512'
